version: '3'

services:

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Lazarus_95
      - MYSQL_DATABASE=springsecurity
      - MYSQL_PASSWORD=Lazarus_95
    ports:
      - 3307:3306
    networks:
      - spring-mysql-mongodb

  mongo:
    image: 'mongo'
    ports:
      - 27017:27017
    hostname: mongo
    networks:
      - spring-mysql-mongodb


  hamburger-api-service:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Lazarus_95
      - DATABASE_NAME=springsecurity
      - DATABASE_PORT=3306
    networks:
      - spring-mysql-mongodb

networks:
  spring-mysql-mongodb:
    driver: bridge
